config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @facade = MarketsFacade.new(params)
  end

  def show 
    @facade = MarketsFacade.new(params)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @facade = MarketsFacade.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<div id='title'>
  <h1 style="text-align: center"> Markets</h1>
</div>

<section id="markets-table">
  <table style="border: 1px solid black; margin: 0 auto;">
    <tr style=>
      <th style="border: 1px solid black">
        Name
      </th>
      <th style="border: 1px solid black">
        City
      </th>
      <th style="border: 1px solid black">
        State
      </th>
      <th style="border: 1px solid black">
      </th>
    </tr>
    <% @facade.markets.each do |market| %>
      <tr>
        <td style="border: 1px solid black;">
          <%= market.name%>
        </td>
        <td style="border: 1px solid black;">
          <%= market.city%>
        </td>
        <td style="border: 1px solid black;">
          <%= market.state %>
        </td>
        <td>
          <%= button_to "More Info", market_path(market.id), method: :get %>
        </td>
      </tr>
      <% end %>
  </table>
</section>

app/views/markets/show.html.erb
<div id="name">
  <h1 style="text-align: center" ><%= @facade.market.name %></h1>
</div>

<div id="address">
  <p style="text-align: center;"> <%= @facade.market.street %> </p>
  <p style="text-align: center;"> <%= @facade.market.city %>, <%= @facade.market.state %> <%= @facade.market.zip %> </p>
</div>
 
<div id="vendors">
  <p> Vendors at our Market: </p>
  <% @facade.vendors.each do |vendor| %>
    <p> <%= link_to "#{vendor.name}", vendor_path(vendor.id) %> <p>
  <% end %>
</div>

app/views/vendors/show.html.erb
<div id="name">
  <h1 style="text-align: center"><%= @facade.vendor.name %></h1>
</div>

<div id="vendor-info">
<p> Contact Info: <br>
    Name: <%= @facade.vendor.contact_name %> <br>
    Phone: <%= @facade.vendor.contact_phone %> </p>
<p> Credit Accepted: <%= @facade.vendor.credit_accepted %> </p>
<p> Description: <%= @facade.vendor.description %> </p>
</div>